[tool.poetry]
name = "videostore"
version = "0.1.0"
description = "Video store kata"
authors = ["Zeger Hendrikse <zegerh@yahoo.co.uk>"]

[tool.poetry.dependencies]
python = ">=3.10.0,<3.12"
pytest = "^7.3.2"
pytest-cov = "^4.1.0"
pytest-watch = "^4.2.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"