[tool.poetry]
name = "repl_python3_ApprovalTestDemo-1"
version = "0.1.0"
description = "Approval test demo"
authors = ["Zeger Hendrikse <zegerh@yahoo.co.uk>"]

[tool.poetry.dependencies]
python = "^3.9"
approvaltests = "^3.2.2"
coverage = "^6.2"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"