[tool.poetry]
name = "Gilded rose"
version = "0.1.0"
description = "Gilded rose kata"
authors = ["Zeger Hendrikse <zegerh@yahoo.co.uk>"]

[tool.poetry.dependencies]
python = ">=3.10.0,<3.12"
mamba = "^0.11.2"
expects = "^0.9.0"
approvaltests = "^9.0.0"
pytest-cov = "^4.1.0"
coverage = "^7.3.2"


[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
