name: Clojure CI

on:
  push:
    branches: [ "master" ]
    paths:
      - '.github/workflows/clojure.yml'
      - 'kata-solutions/connect-four/connect-four-clojure/**'
      - 'kata-solutions/sudoku-kata/sudoku-clojure/**'
      - 'kata-solutions/game-of-life/game-of-life-clojure/**'
      - 'kata-solutions/poker-hands-kata/poker-hands-clojure/**'
      - 'kata-solutions/locker-room-kata/locker-room-clojure/**'
  pull_request:
    branches: [ "master" ]

jobs:
  kata-solution-tests:

    runs-on: ubuntu-latest

    steps:
    - name: Install clojure tools
      uses: DeLaGuardo/setup-clojure@13.2
      with:
        # Install just one or all simultaneously
        # The value must indicate a particular version of the tool, or use 'latest'
        # to always provision the latest version
        cli: 1.10.1.693              # Clojure CLI based on tools.deps
        lein: 2.9.1                  # Leiningen
        boot: 2.8.3                  # Boot.clj
        bb: 0.7.8                    # Babashka
        clj-kondo: 2022.05.31        # Clj-kondo
        cljfmt: 0.10.2               # cljfmt
        cljstyle: 0.16.626           # cljstyle
        zprint: 1.2.3                # zprint
    - uses: actions/checkout@v3
    - name: Connect four kata
      working-directory: kata-solutions/connect-four/connect-four-clojure
      run: lein test
    - name: Sudoku kata
      working-directory: kata-solutions/sudoku-kata/sudoku-clojure
      run: ./run_tests.sh
    - name: Game of life
      working-directory: kata-solutions/game-of-life/game-of-life-clojure
      run: lein test
    - name: Poker hands kata
      working-directory: kata-solutions/poker-hands-kata/poker-hands-clojure
      run: lein test
    - name: Locker room kata
      working-directory: kata-solutions/locker-room-kata/locker-room-clojure
      run: lein test
