name: Clojure CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      working-directory: kata-solutions/connect-four/connect-four-clojure
      run: lein deps
    - name: Run tests
      working-directory: kata-solutions/connect-four/connect-four-clojure
      run: lein test
