# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ "master" ]
    paths:
      - '.github/workflows/gradle.yml'
      - 'kata-solutions/cqrs-booking/cqrs-booking-java/**'
      - 'kata-solutions/sudoku-kata/sudoku-java/**'
      - 'kata-solutions/video-store-kata/video-store-java/**'
      - 'kata-solutions/game-of-life/game-of-life-java/**'
      - 'kata-solutions/stack-kata/stack-kata-java/**'
      - 'kata-solutions/vending-machine/vending-machine-java/**'
      - 'kata-solutions/tell-dont-ask/tell-dont-ask-java/**'

  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build-gradle-project:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout project sources
      uses: actions/checkout@v3
    - name: Setup Gradle
      uses: gradle/gradle-build-action@2.4.2
    - name: Run CQRS booking kata
      working-directory: kata-solutions/cqrs-booking/cqrs-booking-java
      run: ./gradlew test jacocoTestReport
    - name: Run Sudoku kata
      working-directory: kata-solutions/sudoku-kata/sudoku-java
      run: ./gradlew test
    - name: Run video store kata
      working-directory: kata-solutions/video-store-kata/video-store-java
      run: ./gradlew test
    - name: Run game of life kata
      working-directory: kata-solutions/game-of-life/game-of-life-java
      run: ./gradlew test
    - name: Run stack kata
      working-directory: kata-solutions/stack-kata/stack-kata-java
      run: ./gradlew test
    - name: Run vending machine kata
      working-directory: kata-solutions/vending-machine/vending-machine-java
      run: ./gradlew test
    - name: Run tell dont ask kata
      working-directory: kata-solutions/tell-dont-ask/tell-dont-ask-java
      run: ./gradlew test
