name: Node.js CI

on:
  push:
    branches: [ "master" ]
    paths:
      - '.github/workflows/node.js.yml'
      - 'kata-solutions/vending-machine/vending-machine-type/**'
      - 'kata-solutions/vending-machine/vending-machine-javascript/**'
      - 'kata-solutions/stack-kata/stack-kata-javascript/**'
      - 'kata-solutions/gilded-rose-kata/gilded-rose-javascript/1-golden-master/**'
      - 'kata-solutions/gilded-rose-kata/gilded-rose-javascript/2-lift-up-conditional/**'
      - 'kata-solutions/gilded-rose-kata/gilded-rose-javascript/3-gilded-rose-refactored/**'
      - 'kata-solutions/registration-form/registration-form-javascript/**'
      - 'kata-solutions/babysteps-timer/babysteps-typescript/**'
      - 'kata-solutions/countries-kata/countries-kata-javascript/**'
      - 'kata-solutions/countries-kata/countries-kata-typescript/**'
      - 'tdd-katas/babysteps-timer/babysteps-typescript/**'
      - 'tdd-katas/video-store-kata/video-store-javascript/**'
      - 'tdd-katas/video-store-kata/video-store-typescript/**'
  pull_request:
    branches: [ "master" ]

jobs:
  tdd-katas-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Video store kata Javascript with ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - run: | 
        npm ci
        npm test
      working-directory: tdd-katas/video-store-kata/video-store-javascript

    - name: Video store kata Typescript with ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - run: | 
        npm ci
        npm test
      working-directory: tdd-katas/video-store-kata/video-store-typescript

    - name: Babysteps timer kata typescript with ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - run: | 
        npm ci
        npm test
      working-directory: tdd-katas/babysteps-timer/babysteps-typescript

  kata-solutions-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Vending machine kata typescript with ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - run: | 
        npm ci
        npm test
      working-directory: kata-solutions/vending-machine/vending-machine-typescript

    - name: Babysteps timer kata typescript with ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - run: | 
        npm ci
        npm test
      working-directory: kata-solutions/babysteps-timer/babysteps-typescript

    - name: Countries kata Typescript with ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - run: | 
        npm ci
        npm test
      working-directory: kata-solutions/countries-kata/countries-kata-typescript

    - name: Countries kata Javascript with ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - run: | 
        npm ci
        npm test
      working-directory: kata-solutions/countries-kata/countries-kata-javascript

    - name: Vending machine kata Javascript with ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - run: | 
        npm ci
        npm test
      working-directory: kata-solutions/vending-machine/vending-machine-javascript

    - name: Stack kata with ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - run: | 
        npm ci
        npm test
      working-directory: kata-solutions/stack-kata/stack-kata-javascript

    - name: Audio player kata with ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - run: | 
        npm ci
        npm test
      working-directory: kata-solutions/audio-player-kata/audio-player-javascript

    - name: Gilded rose kata part one with ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - run: | 
        npm ci
        npm test
      working-directory: kata-solutions/gilded-rose-kata/gilded-rose-javascript/1-golden-master

    - name: Gilded rose kata part two with ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - run: | 
        npm ci
        npm test
      working-directory: kata-solutions/gilded-rose-kata/gilded-rose-javascript/2-lift-up-conditional

    - name: Gilded rose kata part three with ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - run: | 
        npm ci
        npm test
      working-directory: kata-solutions/gilded-rose-kata/gilded-rose-javascript/3-gilded-rose-refactored

    - name: Registration form with ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - run: | 
        npm ci
        npm test
      working-directory: kata-solutions/registration-form/registration-form-javascript
