name: Python CI

on:
  push:
    branches: [ "master" ]
    paths:
      - '.github/workflows/python.yml'
      - 'kata-solutions/stack-kata/stack-kata-python/**'  
      - 'kata-solutions/sudoku-kata/sudoku-python/**'
      - 'kata-solutions/vending-machine/vending-machine-python/**'
      - 'kata-solutions/bugs-zero-kata/bugs-zero-python/**'
      - 'kata-solutions/cache-kata/cache-kata-python/**'
      - 'kata-solutions/video-store-kata/video-store-python/**'
      - 'kata-solutions/report-generator-kata/report-generator-python/**'
      - 'kata-solutions/gilded-rose-kata/gilded-rose-python/1-golden-master/**'
      - 'kata-solutions/gilded-rose-kata/gilded-rose-python/2-lift-up-conditional/**'
      - 'kata-solutions/gilded-rose-kata/gilded-rose-python/3-gilded-rose-refactored/**'
      - 'kata-solutions/gilded-rose-kata/gilded-rose-python/4-gilded-rose-extended/**'
      - 'kata-solutions/game-of-life/game-of-life-python/**'
      - 'kata-solutions/manhattan-distance/manhattan-distance-python/**'
      - 'kata-solutions/christmas-tree/christmas-tree-python/**'
      - 'kata-solutions/poker-hands-kata/poker-hands-python/**'
      - 'kata-solutions/countries-kata/countries-kata-python/**'
      - 'kata-solutions/questionnaire-kata/questionnaire-python/**'
      - 'tdd-katas/report-generator-kata/report-generator-python/**'
      - 'tdd-katas/video-store-kata/video-store-python/**'
      
  pull_request:
    branches: [ "master" ]

jobs:
  tdd-katas-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ['3.10', '3.11']
    
    steps:
      - name: Check out TDD repository
        uses: actions/checkout@v3
        
      - name: Set up Python with version ${{ matrix.python-version }}
        id: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          
      - name: Install and configure Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true
          
      - name: Report generator kata install dependencies
        working-directory: tdd-katas/report-generator-kata/report-generator-python
        run: poetry install --no-interaction
      - name: Report generator kata run tests
        working-directory: tdd-katas/report-generator-kata/report-generator-python
        run: ./run_tests.sh
          
      - name: Video store kata install dependencies
        working-directory: tdd-katas/video-store-kata/video-store-python
        run: poetry install --no-interaction
      - name: Video store kata run tests
        working-directory: tdd-katas/video-store-kata/video-store-python
        run: ./run_tests.sh
        
  kata-solutions-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ['3.10', '3.11']
    
    steps:
      - name: Check out TDD repository
        uses: actions/checkout@v3
        
      - name: Set up Python with version ${{ matrix.python-version }}
        id: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          
      - name: Install and configure Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true

      - name: Sudoku kata install dependencies
        working-directory: kata-solutions/sudoku-kata/sudoku-python
        run: poetry install --no-interaction
      - name: Sudoku kata run tests
        working-directory: kata-solutions/sudoku-kata/sudoku-python
        run: ./run_tests.sh

      - name: Stack kata install dependencies
        working-directory: kata-solutions/stack-kata/stack-kata-python
        run: poetry install --no-interaction
      - name: Stack kata run tests
        working-directory: kata-solutions/stack-kata/stack-kata-python
        run: ./run_tests.sh
        
      - name: Questionnaire kata install dependencies
        working-directory: kata-solutions/questionnaire-kata/questionnaire-python
        run: poetry install --no-interaction
      - name: Questionnaire kata run tests
        working-directory: kata-solutions/questionnaire-kata/questionnaire-python
        run: ./run_tests.sh

      - name: Vending machine kata install dependencies
        working-directory: kata-solutions/vending-machine/vending-machine-python
        run: poetry install --no-interaction
      - name: Vending machine kata run tests
        working-directory: kata-solutions/vending-machine/vending-machine-python
        run: ./run_tests.sh

      - name: Bugs zero kata install dependencies
        working-directory: kata-solutions/bugs-zero-kata/bugs-zero-python
        run: poetry install --no-interaction
      - name: Bugs zero kata run tests
        working-directory: kata-solutions/bugs-zero-kata/bugs-zero-python
        run: ./run_tests.sh
     
      - name: Manhattan distance kata install dependencies
        working-directory: kata-solutions/manhattan-distance/manhattan-distance-python
        run: poetry install --no-interaction
      - name: Manhattan distance kata run tests
        working-directory: kata-solutions/manhattan-distance/manhattan-distance-python
        run: ./run_tests.sh
     
      - name: Cache kata install dependencies
        working-directory: kata-solutions/cache-kata/cache-kata-python
        run: poetry install --no-interaction
      - name: Cache kata run tests
        working-directory: kata-solutions/cache-kata/cache-kata-python
        run: poetry run pytest 
     
      - name: Video store kata install dependencies
        working-directory: kata-solutions/video-store-kata/video-store-python
        run: poetry install --no-interaction
      - name: Video store kata run tests
        working-directory: kata-solutions/video-store-kata/video-store-python
        run: ./run_tests.sh
          
      - name: Poker hands kata install dependencies
        working-directory: kata-solutions/poker-hands-kata/poker-hands-python
        run: poetry install --no-interaction
      - name: Poker hands kata run tests
        working-directory: kata-solutions/poker-hands-kata/poker-hands-python
        run: ./run_tests.sh
          
      - name: Countries kata install dependencies
        working-directory: kata-solutions/countries-kata/countries-kata-python
        run: poetry install --no-interaction
      - name: Countries kata run tests
        working-directory: kata-solutions/countries-kata/countries-kata-python
        run: ./run_tests.sh
          
      - name: Game of Life kata install dependencies
        working-directory: kata-solutions/game-of-life/game-of-life-python
        run: poetry install --no-interaction
      - name: Game of Life kata run tests
        working-directory: kata-solutions/game-of-life/game-of-life-python
        run: ./run_tests.sh
          
      - name: Christmas tree kata install dependencies
        working-directory: kata-solutions/christmas-tree/christmas-tree-python
        run: poetry install --no-interaction
      - name: Christmas tree kata run tests
        working-directory: kata-solutions/christmas-tree/christmas-tree-python
        run: ./run_tests.sh
        
      - name: Report generator kata install dependencies
        working-directory: kata-solutions/report-generator-kata/report-generator-python
        run: poetry install --no-interaction
      - name: Report generator kata run tests
        working-directory: kata-solutions/report-generator-kata/report-generator-python
        run: ./run_tests.sh
          
      - name: Gilded rose kata part one install dependencies
        working-directory: kata-solutions/gilded-rose-kata/gilded-rose-python/1-golden-master
        run: poetry install --no-interaction
      - name: Gilded rose kata part one run tests
        working-directory: kata-solutions/gilded-rose-kata/gilded-rose-python/1-golden-master
        run: ./run_tests.sh
      - name: Gilded rose kata part two install dependencies
        working-directory: kata-solutions/gilded-rose-kata/gilded-rose-python/2-lift-up-conditional
        run: poetry install --no-interaction
      - name: Gilded rose kata part two run tests
        working-directory: kata-solutions/gilded-rose-kata/gilded-rose-python/2-lift-up-conditional
        run: ./run_tests.sh
      - name: Gilded rose kata part three install dependencies
        working-directory: kata-solutions/gilded-rose-kata/gilded-rose-python/3-gilded-rose-refactored
        run: poetry install --no-interaction
      - name: Gilded rose kata part three run tests
        working-directory: kata-solutions/gilded-rose-kata/gilded-rose-python/3-gilded-rose-refactored
        run: ./run_tests.sh
      - name: Gilded rose kata part four install dependencies
        working-directory: kata-solutions/gilded-rose-kata/gilded-rose-python/4-gilded-rose-extended
        run: poetry install --no-interaction
      - name: Gilded rose kata part four run tests
        working-directory: kata-solutions/gilded-rose-kata/gilded-rose-python/4-gilded-rose-extended
        run: ./run_tests.sh


